[project]
authors = [
    {name = "Your Name", email = "you@example.com"},
]
requires-python = "<4.0,>=3.12"
dependencies = [
    "django<6.0,>=5.2",
    "pillow<12.0.0,>=11.2.1",
    "python-decouple<4.0,>=3.8",
    "gunicorn<24.0.0,>=23.0.0",
    "whitenoise<7.0.0,>=6.11.0",
    "psycopg[binary]<4.0.0,>=3.3.2",
    "django-storages<2.0.0,>=1.14.6",
    "boto3<2.0.0,>=1.42.12",
    "olefile<1.0,>=0.47",
    "pillow-avif-plugin<2.0.0,>=1.5.2",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "django-cors-headers>=4.9.0",
    "pytest-django>=4.11.1",
]
name = "project1"
version = "0.1.0"
description = ""

[dependency-groups]
dev = [
    "parameterized<1.0.0,>=0.9.0",
    "coverage<8.0.0,>=7.9.1",
    "django-stubs>=5.2.1,<6.0.0",
    "mypy-extensions<2.0.0,>=1.1.0",
    "mypy<2.0.0,>=1.16.1",
    "selenium<5.0.0,>=4.35.0",
    "pyrefly>=0.50.0",
    "pytest>=8.4.2",
    "pytest-django>=4.11.1",
    "faker>=40.1.2",
    "django-debug-toolbar>=6.2.0",
    "pytest-watcher>=0.6.3",
]

[tool.pdm]
distribution = false

[tool.pdm.build]
includes = []
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pyrefly.errors]
missing-attribute = false
bad-assignment = false
bad-return = false
unknown-name = false
bad-argument-type = false
bad-override = false

[tool.ruff]
line-length = 88
target-version = "py312"
fix = true
show-fixes = true
indent-width = 4
exclude = ["__pycache__", "migrations", ".venv", ".env-example"]

[tool.ruff.lint]
select = [
    "ASYNC",
    "A",
    "ANN",
    "B",
    "BLE",
    "C4",
    "C90",
    "COM",
    "DJ",
    "E",
    "EM",
    "ERA",
    "EXE",
    "F",
    "FBT",
    "FIX",
    "I",
    "ICN",
    "ISC",
    "Q",
    "RET",
    "RSE",
    "S",
    "SIM",
    "SLF",
    "T10",
    "T20",
    "TC",
    "TD",
    "TRY",
    "UP",
    "W",
    "YTT",
    "RUF",
    "N",
]
ignore = ["ANN002", "ANN003"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["ANN201", "S101"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.basedpyright]
typeCheckingMode = "strict"
pythonVersion = "3.12"
include = ["."]
exclude = ["**/__pycache__"]
reportAttributeAccessIssue = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownParameterType = "none"
reportMissingParameterType = "none"
reportUnknownArgumentType = "none"
reportUnusedImport = "none"
reportMissingTypeArgument = "none"
reportUntypedFunctionDecorator = "none"

[tool.coverage.run]
branch = true
omit = [
    "venv/*",
    "**/*test*.py",
    "manage.py",
    "**/migrations/*.py",
    "utils/browser.py",
    "tests/functional_tests/recipes/base.py",
    "tests/functional_tests/authors/base.py"
]

[tool.pytest-watcher]
now = false
clear = true
notify_on_failure = false
delay = 0.2
runner = "pytest"
patterns = ["*.py"]
runner_args = ["recipes/tests.py", "-rP"]
ignore_patterns = [".venv", ".git", "__pycache__", "locale"]
