# Generated by Django 5.2 on 2025-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(default='Porções', max_length=65),
            preserve_default=False,
        ),
    ]
