# Generated by Django 5.2 on 2025-05-24 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_servings_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='praparation_steps',
            new_name='preparation_steps',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='praparation_steps_is_html',
            new_name='preparation_steps_is_html',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d'),
        ),
    ]
