# Generated by Django 5.2 on 2025-12-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time_unit',
            field=models.CharField(choices=[('Minutos', 'Minutos'), ('Horas', 'Horas')], max_length=65),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings_unit',
            field=models.CharField(choices=[('Porções', 'Porções'), ('Pedaços', 'Pedaços'), ('Pessoas', 'Pessoas')], max_length=65),
        ),
    ]
